CREATE TABLE IF NOT EXISTS public.WEB_STAT (
     "HOST" CHAR(2) NOT NULL,
     "DOMAIN" VARCHAR NOT NULL,
     FEATURE VARCHAR NOT NULL,
     "DATE" DATE NOT NULL,
     CORE BIGINT,
     DB BIGINT,
     ACTIVE_VISITOR INTEGER,
     PRIMARY KEY ("HOST", "DOMAIN", FEATURE, "DATE")
);
